version: '3.8'

services:
  db:
    image: postgres:15
    container_name: whatizeDev_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: whatize
      POSTGRES_USER: whatize
      POSTGRES_PASSWORD: ZdG387FhYsm0olSm097541HMSdS=
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - '25432:5432'  # porta local exclusiva para esse Postgres
    volumes:
      - whatize_postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - whatize_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U whatize -d whatize"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: whatizeDev_redis
    restart: unless-stopped
    command: redis-server --requirepass ZdG387FShYsm0SaaSoRlSAAsme09a754s1DHMSsIdS= --appendonly yes
    ports:
      - "60123:6379"  # porta local exclusiva para esse Redis
    volumes:
      - whatize_redis_data:/data
    networks:
      - whatize_net
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  whatize_postgres_data:
    driver: local
  whatize_redis_data:
    driver: local

networks:
  whatize_net:
    driver: bridge
